apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Common labels for all resources
commonLabels:
  app: podinfo
  owner: boro

# List of resource files to include
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml 