apiVersion: v2
name: podinfo-chart
description: A Helm chart for Podinfo application
type: application
version: 0.1.0
appVersion: "v1.0.0"
keywords:
  - podinfo
  - microservice
home: https://github.com/stefanprodan/podinfo
sources:
  - https://github.com/stefanprodan/podinfo
maintainers:
  - name: Your Name
    email: your-email@example.com 