# Default values for podinfo-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

namespace:
  create: true
  name: ptest

image:
  repository: stefanprodan/podinfo
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9898
  targetPort: 9898
  name: http

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

probes:
  liveness:
    enabled: true
    httpGet:
      path: /healthz
      port: 9898
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    enabled: true
    httpGet:
      path: /readyz
      port: 9898
    initialDelaySeconds: 5
    periodSeconds: 10

podLabels:
  version: v1.0.0 
  owned-by: boro