apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base layer
bases:
  - ../../base

# Namespace for prod environment
namespace: podinfo-prod

# Name prefix for all resources
namePrefix: prod-

# Common labels for prod environment
commonLabels:
  environment: production
  team: ops-team

# Patches to customize resources for prod
patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml

# Replace the namespace name
patches:
  - target:
      kind: Namespace
      name: podinfo-base
    patch: |-
      - op: replace
        path: /metadata/name
        value: podinfo-prod

# ConfigMap for prod-specific configuration
configMapGenerator:
  - name: podinfo-config
    literals:
      - environment=production
      - log_level=info
      - feature_flags=stable

# Add production-specific replica count
replicas:
  - name: podinfo
    count: 3 