---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  labels:
    app: podinfo
  namespace: ptest
spec:
  type: ClusterIP
  selector:
    app: podinfo
  ports:
  - port: 9898
    targetPort: 9898
    protocol: TCP
    name: http